version: '3.9'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /srv/media:/srv
      #- type: bind
      #source: ./filebrowser.db
      #target: /database/filebrowser.db
      #      - type: bind
      #source: ./settings.json
      #target: /config/settings.json
    environment:
      - PUID=$$(id -u)
      - PGID=$$(id -g)
    ports:
      - 8095:80
    networks:
      - filebrowser-net
networks:
  filebrowser-net:
    external: false
    name: filebrowser-net
