#!/bin/bash



# Symlink the service file to the correct location
# sudo ln -s /home/pi/home-assistant-config/ha.service /etc/systemd/system/ha.service

# Enable the service
# sudo systemctl enable ha.service

 
declare -r DIR="/srv/stacks/filebrowser"

start() {
    cd ${DIR}
 
    docker-compose up -d
}
 
stop() {
    cd ${DIR}
    docker-compose stop
}
 
case $1 in
    start) start;;
    stop) stop;;
    "") start;;
    *) echo "Usage: ./service start|stop"
esac
