#!/bin/bash


declare -r DIR="/srv/stacks/filebrowser"

start() {
    cd ${DIR}
 
    docker-compose up -d
}
 
stop() {
    cd ${DIR}
    docker-compose stop
}
 
case $1 in
    start) start;;
    stop) stop;;
    "") start;;
    *) echo "Usage: ./service start|stop"
esac
