version: '3'

services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - ${RADARR_CONFIG}:/config
    - ${MOVIES_FOLDER}:/movies
    - ${TORRENTS_FOLDER}:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Amsterdam
  image: linuxserver/radarr
 
