 services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"
    volumes:
      - ${PROWLARR_CONFIG}:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000 
