version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${CADDYFILE}:/etc/caddy/Caddyfile
      - $WWW:/srv
      - ${CADDY_CONFIG}/caddy_data:/data
      - ${CADDY_CONFIG}/caddy_config:/config
      - ${CADDY_CONFIG}/log:/var/log/caddy:rw
    networks:
      - services_network

networks:
  services_network:
    name: services_network

volumes:
  caddy_data:
  caddy_config:
