#!/bin/bash

declare -r DIR=$(dirname $(realpath ${BASH_SOURCE}))

start() {
    cd ${DIR}
 
    docker-compose up -d --remove-orphans
}
 
stop() {
    cd ${DIR}
    docker-compose stop
}
 
case $1 in
    start) start;;
    stop) stop;;
    "") start;;
    *) echo "Usage: ./service start|stop"
esac
