services:
  deluge:
    container_name: deluge
    environment:
      DELUGE_LOGLEVEL: error
      PGID: '1000'
      PUID: '1000'
      TZ: Etc/UTC
    image: lscr.io/linuxserver/deluge:latest
    ports:
    - published: 8112
      target: 8112
    - published: 6881
      target: 6881
    - protocol: udp
      published: 6881
      target: 6881
    - published: 58846
      target: 58846
    restart: unless-stopped
    volumes:
    - /srv/stacks/src/deluge/config:/config:rw
    - /srv/media/torrents.complete:/downloads:rw
version: '3.9'
