version: '3.9'

services:
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
    - 8989:8989
  volumes:
    - ${SONARR_CONFIG}:/config
    - ${TV_FOLDER}:/tv
    - ${TORRENTS_FOLDER}:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Amsterdam
  image: linuxserver/sonarr:latest
 
