# https://docs.linuxserver.io/images/docker-jellyfin/

---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /srv/stacks/jellyfin/library:/config
      - /srv/media/tvshows:/data/tvshows
      - /srv/media/movies:/data/movies
    ports:
      - 8096:8096
        # - 8920:8920 #optional
        # - 7359:7359/udp #optional
        # - 1900:1900/udp #optional
    restart: unless-stopped
